### PR TITLE
Replace makefile and configure with single run script

### PR DESCRIPTION
**Pull request by ninewise**
Since make does not remove intermediate files during execution, we were
using up a lot more space than required. The new script fixes the order
of execution. This allows removing intermediate files during execution.
On the downside, this makes it more work to build only parts of the
database.

### CODE REVIEW

**Review by pverscha — CHANGES_REQUESTED** [review]
We should also update the `static_database` workflow, which uses some of the deleted files to build a small database that contains information that is not updated regularly (such as the mapping between gene ontology ID's and their namespace, name, etc.). This PR breaks the workflow at this moment.

**Comment by ninewise** [comment]
Oh I searched for usages, but my searcher skips hidden files. I'll have a look.

**Comment by ninewise** [comment]
I've made some changes so I could use the script for the static database, too.

Is there a specific reason the `build_database.sh` workflow script is a separate script and not just inlined in the yml file?

**Comment by pverscha** [comment]
I initially did not inline `build_database.sh` in the yml-file for debugging purposes (so that I didn't have to run the GitHub-action, which is actually possible using [this repository](https://github.com/nektos/act), but takes a long time...). I guess, however, that we can decide to inline the script at this point in time :)

**Comment by ninewise** [comment]
OK, I inlined it now - let's hope we don't have to debug again.

**Review by pverscha — APPROVED** [review]

**Pull request merged**
